services:
  # Serves public/ and forwards PHP to php-fpm
  nginx:
    image: nginx:1.26-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-statamic}-nginx
    ports:
      - "${DEV_HTTP_PORT:-8082}:80"          # Visit http://localhost:8082
    volumes:
      - ./app:/var/www/html                  # Share code into container
      - ./nginx/site.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      php:
        condition: service_started
    networks:
      - app_net_dev
    restart: unless-stopped

  # Runs PHP (Statamic/Laravel app)
  php:
    build:
      context: ./php
      dockerfile: Dockerfile.dev
    container_name: ${COMPOSE_PROJECT_NAME:-statamic}-php
    environment:
      TZ: ${TZ:-Australia/Melbourne}
      AUTO_INSTALL: ${AUTO_INSTALL:-1}         # If you script auto-install, flip on
      LARAVEL_VERSION: ${LARAVEL_VERSION:-}    # Ignored if you install Statamic directly
      # DB vars passed so entrypoint can write app/.env on first run
      MYSQL_DATABASE: ${MYSQL_DATABASE:-appdb}
      MYSQL_USER: ${MYSQL_USER:-appuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-apppass}
      DEV_HTTP_PORT: ${DEV_HTTP_PORT:-8082}
    volumes:
      - ./app:/var/www/html
      - composer-cache-statamic:/tmp/composer  # Separate cache from Laravel stack
      - ./php/conf.d/local.ini:/usr/local/etc/php/conf.d/zz-local.ini:ro
      # Optional Xdebug — rename & uncomment to enable
      # - ./php/conf.d/xdebug.ini.example:/usr/local/etc/php/conf.d/zz-xdebug.ini:ro
    expose:
      - "9000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_net_dev
    restart: unless-stopped

  # MySQL database
  mysql:
    image: mysql:8.0
    container_name: ${COMPOSE_PROJECT_NAME:-statamic}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-appdb}
      MYSQL_USER: ${MYSQL_USER:-appuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-apppass}
    volumes:
      - mysql-data-statamic:/var/lib/mysql     # Separate DB volume from Laravel stack
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - app_net_dev
    restart: unless-stopped

  # Web DB GUI for MySQL — use when you don't have Navicat etc.
  phpmyadmin:
    image: phpmyadmin:5-apache
    container_name: ${COMPOSE_PROJECT_NAME:-statamic}-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER:-appuser}
      PMA_PASSWORD: ${MYSQL_PASSWORD:-apppass}
    ports:
      - "${PHPMYADMIN_PORT:-8083}:80"          # Visit http://localhost:8083
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_net_dev
    restart: unless-stopped

volumes:
  composer-cache-statamic:
  mysql-data-statamic:

networks:
  app_net_dev:
    name: ${COMPOSE_PROJECT_NAME:-statamic}_dev_net
    driver: bridge