CREATE DATABASE IF NOT EXISTS directus CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'directus'@'%' IDENTIFIED BY 'directuspass';
GRANT ALL PRIVILEGES ON directus.* TO 'directus'@'%';
FLUSH PRIVILEGES;
